# We are using now semantic versioning
environment:
  core_version: 1.0.4
  COVERALL_TOKEN:
    secure: fCYgOFdulN+Oy2egpNLEMPLM/CZceyDfIRXkx/IkphthEUHHeBhaK49jFw3Y1AZZ

version: "$(core_version)+{branch}+{build}"

branches:
  only:
    - master

# This will speed up nuget package restore
cache:
  - packages -> **\packages.config

skip_tags: true

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(core_version)"
  assembly_file_version: "$(core_version)"
  assembly_informational_version: "{version}"

configuration: Release

test: off

test_script:
  - ps: .\runtests.ps1

before_build:
  - ps: nuget restore

build:
  project: SimpleConf.sln
  verbosity: minimal
