version: 1.0.{build}

branches:
  only:
    - master

cache:
  - packages -> **\packages.config

skip_tags: true

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - ps: nuget restore

build:
  project: configurator.sln
  verbosity: minimal
  publish_nuget: true
